### PR TITLE
Fix viewonline_overwrite_location/Change posting template

### PR DESCRIPTION
**Pull request by dmzx**

### CODE REVIEW

**Comment by kinerity** [comment]
Can you split these up into separate PRs please? Also, you may want to wait until I push the new version (about a week) as a lot of the extension was re-written.  :)

**Comment by dmzx** [comment]
A ok np ;) maybe you can use the posting template fix.

**Comment by kinerity** [comment]
I'll let you submit a PR once it's pushed - you can take the credit for it.

**Comment by dmzx** [comment]
No need for that you can add if you want np.
Will check it when you pushed it if its there ;) otherwise I will PR it again.

**Pull request closed without merging**
